# enable serial console in kernel config
kernel_do_configure:prepend() {
	if [ "${SERIAL_DEBUG}" = "yes" ] && [ -f ${UNPACKDIR}/defconfig ]; then
		sed -i -e \
			's/^CONFIG_TTY=.*/CONFIG_TTY=y/
			 s/^# CONFIG_TTY .*/CONFIG_TTY=y/
			 s/^CONFIG_VT=.*/CONFIG_VT=y/
			 s/^# CONFIG_VT .*/CONFIG_VT=y/
			 s/^CONFIG_CONSOLE_TRANSLATIONS=.*/CONFIG_CONSOLE_TRANSLATIONS=y/
			 s/^# CONFIG_CONSOLE_TRANSLATIONS .*/CONFIG_CONSOLE_TRANSLATIONS=y/
			 s/^CONFIG_VT_CONSOLE=.*/CONFIG_VT_CONSOLE=y/
			 s/^# CONFIG_VT_CONSOLE .*/CONFIG_VT_CONSOLE=y/
			 s/^CONFIG_VT_CONSOLE_SLEEP=.*/CONFIG_VT_CONSOLE_SLEEP=y/
			 s/^# CONFIG_VT_CONSOLE_SLEEP .*/CONFIG_VT_CONSOLE_SLEEP=y/
			 s/^CONFIG_HW_CONSOLE=.*/CONFIG_HW_CONSOLE=y/
			 s/^# CONFIG_HW_CONSOLE .*/CONFIG_HW_CONSOLE=y/
			 s/^CONFIG_VT_HW_CONSOLE_BINDING=.*/CONFIG_VT_HW_CONSOLE_BINDING=y/
			 s/^# CONFIG_VT_HW_CONSOLE_BINDING .*/CONFIG_VT_HW_CONSOLE_BINDING=y/
			 s/^CONFIG_UNIX98_PTYS=.*/CONFIG_UNIX98_PTYS=y/
			 s/^# CONFIG_UNIX98_PTYS .*/CONFIG_UNIX98_PTYS=y/' \
		${UNPACKDIR}/defconfig
	fi
}
